name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to VS Marketplace"
        type: boolean
        required: true
        default: true

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    outputs:
      packageName: ${{ steps.setup.outputs.packageName }}
      version: ${{ steps.setup-tag.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm ci
          npm install --save-dev vsce
      - name: Setup package path
        id: setup
        run: echo "packageName=$(node -e "console.log(require('./package.json').name + '-' + require('./package.json').version + '.vsix')")" >> $GITHUB_OUTPUT
      - name: Package
        run: npx vsce package --out ${{ steps.setup.outputs.packageName }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup.outputs.packageName }}
          path: ./${{ steps.setup.outputs.packageName }}
          if-no-files-found: error
      - name: Setup tag
        id: setup-tag
        shell: pwsh
        run: |
          $version = (Get-Content ./package.json -Raw | ConvertFrom-Json).version
          "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

  publishMS:
    name: Publish to VS Marketplace
    runs-on: ubuntu-latest
    needs: package
    if: github.event.inputs.publish == 'true' || github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.package.outputs.packageName }}
      - name: Publish to VS Marketplace
        run: npx vsce publish --packagePath ./${{ needs.package.outputs.packageName }} -p ${{ secrets.VSCE_PAT }}
